archive:
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: 32-bit
    amd64: 64-bit
snapshot:
  name_template: "{{ .Tag }}-next"
brew:
  github:
    owner: Ilyes512
    name: homebrew-goreleaserpoc
  folder: Formula
  homepage: https://github.com/Ilyes512/goreleaserpoc
  description: "A simple Go app to test out GoReleaser (POC)"
builds:
  ldflags:
    - -s -w -X github.com/Ilyes512/goreleaserpoc/pkg/configuration.Version={{.Version}} -X github.com/Ilyes512/goreleaserpoc/pkg/configuration.Commit={{.Commit}} -X github.com/Ilyes512/goreleaserpoc/pkg/configuration.Date={{.Date}}
